name: Deploy Application

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Contabo
        run: |
          ssh -o StrictHostKeyChecking=no user@your-contabo-ip "
            cd /home/projects/supermario_shop &&
            git pull origin main &&
            source venv/Scripts/activate &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            sudo systemctl restart gunicorn"  # Asegúrate de que gunicorn esté configurado para reiniciar con systemctl
